### ISSUE TITLE
"Save" button works erratically when clicked for newly created studies in Chrome/Edge

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#101]
To reproduce:
* Open Chrome or Edge (please note that Chrome or Edge are the only officially supported browsers for the Save feature, to overwrite an existing study/graphml).
* Create a study by clicking "+" and adding a few nodes and edges.
* Click "Save"
* It says, "Switch to Edge/Chrome!"

The expected behavior:
* When you click "Save" on a newly created study/graphml, the "Save" should function in the same way as "Save As" and let you choose the output directory and study name (as in studyname.graphml).

This issue is only for newly visually created graphml files (i.e., studies). The already existing ones work fine.
* When you click "Save" on an existing (already locally saved) study in Chrome, the study should be saved (i.e., overwrite the existing graphml in the same folder. No duplicate files). This one works without trouble.
*  When you click "Save As" on an existing (already locally saved) study, it lets you choose the output directory and study name (as in studyname.graphml). This one also works without trouble.

**Comment by Rahuljagwani** [comment]
@pradeeban can u please assign this issue to me?

**Comment by pradeeban** [comment]
Fixed by #103.
