### ISSUE TITLE
all graphML filesopend have same author name

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#105]
Reproduce

1. open or create various graphML files
2. try to change author name

you will notice that author name for the files will be same means you can't give different author name to different graphml files

@pradeeban please assign this issue , if this feature is not working as required by concore-editor

**Comment by pradeeban** [comment]
Hi @parteekcoder,
Your approach sounds good to me. It is weird that changing the author of a single graph changes all of them in how we have it currently.

**Comment by parteekcoder** [comment]
@pradeeban Actually now it is implemented as single `authorName` for superState so changing one will change all

**Comment by pradeeban** [comment]
No idea why it was implemented like that. It could be an oversight or a rationale behind that...

**Comment by pradeeban** [comment]
Tested and merged.
