### ISSUE TITLE
hotKey bug

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#108]
@pradeeban 

Reproduce:
1. trigger `clear` hotkey

You will find an error like this and that key is not triggered
![image](https://user-images.githubusercontent.com/100110395/221912850-74e0c41b-bbec-4325-a456-a44a600b8877.png)

Reason :
Dur to this line https://github.com/ControlCore-Project/concore-editor/blob/main/src/component/Header.jsx#L20
Our keys are like this 
```
Ctrl+G,Command+G,Ctrl+O,Command+O,Ctrl+Backspace,Command+Backspace,Ctrl+Z,Command+Z,Ctrl+Shift+Z,Command+Shift+Z,Ctrl+Y,Command+Y,Ctrl+E,Command+E,Delete,Delete,Backspace,Backspace,Del,Del,Clear,Clear,
```
But it should be 
```
Ctrl+G,Command+G,Ctrl+O,Command+O,Ctrl+Backspace,Command+Backspace,Ctrl+Z,Command+Z,Ctrl+Shift+Z,Command+Shift+Z,Ctrl+Y,Command+Y,Ctrl+E,Command+E,Delete,Delete,Backspace,Backspace,Del,Del,Clear,Clear
```
So that's why it is not able to trigger `clear,` which is last key as seen above

**Comment by pradeeban** [comment]
Merged to main.
