### ISSUE TITLE
The "Contribute" button is hard-coded to https://github.com/ControlCore-Project/concore-editor

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#113]
The "Contribute" button should invoke a "Contribute" action, which is yet to be implemented. 

Currently, it is taking us to the hard-coded URL of https://github.com/ControlCore-Project/concore-editor
This is misleading even for a hard-coded URL.

The fix is to replace this hard-coded URL with https://github.com/ControlCore-Project/concore instead. Because the idea of "Contribute" is to contribute your studies and programs (which will eventually live in the concore repository). It has nothing to do with the concore-editor repository.

**Comment by parteekcoder** [comment]
ok @pradeeban I will create PR for this

And will also help to implement this properly as you were mentioning yesterday

**Comment by pradeeban** [comment]
Thanks for the effort! I have assigned you this bug.

**Comment by pradeeban** [comment]
Fixed in #114.

**Comment by parteekcoder** [comment]
thanks @pradeeban for merging, will discuss for this in the discussion
