### ISSUE TITLE
Saving files not working properly

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#119]
hey @pradeeban 

Reproduce:
1. Craete some new Graphml files
2. Save 1 file
3. Now try to save another file

Actual : You will find that another file is also automatically saved but it should have asked for file location as it is saved first time

Problem: When we save one file , it is setting same fileHandler for all the files

Expected: It should save each file independently 

Reason: 
here this fucntion https://github.com/ControlCore-Project/concore-editor/blob/main/src/graph-builder/graph-core/5-load-save.js#L130

@pradeeban please assign if it is not working as required by the concore-editor

**Comment by pradeeban** [comment]
Merged to main.
