### ISSUE TITLE
removing alert statements

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#121]
@pradeeban 

As alert statements degrades user experience , I am removing them

**Comment by pradeeban** [comment]
That removed the alert, but did not introduce the flash in Firefox. So, I have closed the PR. Please open a new one that is tested on Firefox also.

**Comment by parteekcoder** [comment]
Yeah , I sorry for the inconvenience caused to you , i will update that PR

**Comment by pradeeban** [comment]
No worries, and no rush. Feel free to take your time.

**Comment by pradeeban** [comment]
merged to main.
