### ISSUE TITLE
Unable to change the workflow name of an existing graphml file

### ISSUE THREAD

**Issue by TC5022** [ControlCore-Project/concore-editor#124]
Once a graphml file has been saved to the system of the user, it is not possible to change its workflow name from the editor. To reproduce:
- create a new workflow and save it.
- try to reopen it and change its name.

![image](https://user-images.githubusercontent.com/75262300/222919383-d9d6c0bb-d724-4ba7-b1e6-307b340b7aa8.png)

![image](https://user-images.githubusercontent.com/75262300/222919414-337df139-7d3e-48ce-a52e-ddb827d29547.png)

even though the name has been changed in the project details modal, it doesn't reflect in the main window. I don't think that this is desired behavior. Either the user should not be allowed to change the workflow name at all or we should be allowed to uniformly change the file name.

**Comment by TC5022** [comment]
@pradeeban kindly let me know if this is a potential bug and I will be happy to solve it. Thanks for your time.

**Comment by pradeeban** [comment]
The workflow name and the file name are different things. You can change the workflow name (reflected in the blue bar in the top). Just the file name cannot be changed.

If you look at the top blue bar, you can see that change being reflected. Allowing the file change from the browser is a bit more difficult and differs across browsers. It will be achievable in Chrome/Edge, but not in Firefox as of the current implementation.

To avoid creating further confusions, we don't change the graphml file name, but just the workflow name this way.

Closing as "Won't Fix" for now.
