### ISSUE TITLE
 "Save" button works erratically when clicked for pre-loaded studies in Chrome/Edge

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#127]
Please check  #101. The fix for this issue is probably something similar to what is done to fix #101.

To reproduce:

Open Chrome or Edge (please note that Chrome or Edge are the only officially supported browsers for the Save feature, to overwrite an existing study/graphml).
Load a study/graphml
    Close the browser.
Reopen the browser. 
If your browser is configured to open the previous tabs, it will open the concore-editor with that study that you opened before.
Now, make some changes, and click "Save"
    It says, "Switch to Edge/Chrome!"

The expected behavior:

When you click "Save" on such a study/graphml, the "Save" should function in the same way as "Save As" and let you choose the output directory and study name (as in studyname.graphml).

This issue is only for studies that are loaded like this from the previous session. (You can reproduce this issue only if your browser opens the previous session when the browser is opened).

**Comment by parteekcoder** [comment]
hey @pradeeban this is caused as fileHandler get vanish on reloading ,

Please assign I will try my best with the optimal possible solution

**Comment by parteekcoder** [comment]
One solution is to again choose the file directory if there is not fileHandle present

**Comment by pradeeban** [comment]
This should probably be handled similar to how # #101 was handled - making "Save" behave as a "Save As."
 
Can you please deploy your fix to your GitHub so I can test it?

**Comment by parteekcoder** [comment]
> This should probably be handled similar to how # #101 was handled - making "Save" behave as a "Save As."
> 
> Can you please deploy your fix to your GitHub so I can test it?

you mean that If there is not fileHandle we should call `save As` in all cases(means in all browser)

**Comment by parteekcoder** [comment]
what I have done in my PR:
- if there is fileHandle 
           it simply saves
- if there is not fileHandle
          in chrome/edge it should again ask for the filePicker
          in firefox it says to switch to chrome and edge

**Comment by pradeeban** [comment]
> what I have done in my PR:
> 
>     * if there is fileHandle
>       it simply saves
> 
>     * if there is not fileHandle
>       in chrome/edge it should again ask for the filePicker
>       in firefox it says to switch to chrome and edge

I like your approach. Please deploy it in your GitHub. I will test it.

**Comment by parteekcoder** [comment]
yeah deployed you can test at https://parteekcoder.github.io/concore-editor/

**Comment by parteekcoder** [comment]
@pradeeban Also I have a suggestion that I also proposed before that in firefox 

`save` button should be implemented like `save as` button

**Comment by pradeeban** [comment]
> @pradeeban Also I have a suggestion that I also proposed before that in firefox
> 
> `save` button should be implemented like `save as` button

Thanks for the fix, @parteekcoder.

I don't understand your proposal. Will not then be a mere duplicate "Save As" button in Firefox then?

**Comment by pradeeban** [comment]
Then there is no need to attempt at this. The current Save functionality supported by Chrome is critical, as it creates a natural integration between concore and concore editor. This feature does not exist in Firefox. For now, we can live with the "Switch to Edge/Chrome" alert.
