### ISSUE TITLE
Disable the "Contribute" button when the workspace is literally empty (when no studies/graphml or programs/folders in concore editor).

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#141]
Currently, the "Contribute" button just links to the GitHub repository of concore. But eventually this will invoke the contribute action.

Therefore, this button should become active only when something is loaded into the concore repository.

That means either,
* A folder is uploaded into the concore editor (so it has some files, any files).
or
* A study/graphml is created or loaded into the concore editor.

The solution might be similar to #104. But extra-care is needed because we should activate this button even if there is no graphml present, if a folder is loaded. (because the contributions can be studies or programs).

This is a low-priority issue. But reported for documentation purposes.

**Comment by Rahuljagwani** [comment]
I will be sending a PR regarding this shortly

**Comment by pradeeban** [comment]
Merged. Thanks.
