### ISSUE TITLE
Graph is going out of view when clicking just left button of centre in bottom -right corner

### ISSUE THREAD

**Issue by shivprime94** [ControlCore-Project/concore-editor#149]
@pradeeban Suppose the user made a graph like this
![image](https://user-images.githubusercontent.com/73483959/227697502-67c197b2-483e-4d9c-8de8-7f9e7bab48e6.png)

Now if we press that button, it gets out of the view of the screen like this
![image](https://user-images.githubusercontent.com/73483959/227697646-2317a705-10b7-4be8-8c68-af72cf285c5d.png)

The left-most button 
![image](https://user-images.githubusercontent.com/73483959/227697691-81083d83-594b-4b64-a0a7-a6d16c3d155f.png)

Node version:  v16.19.1
OS : Ubuntu 22.04.2 LTS
React  ^17.0.2

**Comment by pradeeban** [comment]
Good catch. No idea what that button is for. I have never used it.

**Comment by parteekcoder** [comment]
@pradeeban @shivprime94 These are zoom in and zoom out buttons, that's why when you click that it gets zoom out

**Comment by pradeeban** [comment]
@shivprime94 is referring to that left-most circle-like button. Just click it around, following the exact steps he did (even replicating the graph shape).

Then you will encounter the same bug. The top-most node will go out of frame.

**Comment by pradeeban** [comment]
I think, the button is trying to refocus. But the top-most node goes off the frame when it does that. That is an annoying bug if someone uses this button.

**Comment by parteekcoder** [comment]
> I think, the button is trying to refocus. But the top-most node goes off the frame when it does that. That is an annoying bug if someone uses this button.

yes you are right these buttons focus or zoom the content, and that's why the alignment issue arises when clicked  

As our current zooming strategy is not based on the position of the graph
