### ISSUE TITLE
UI overflow as well as background color not working

### ISSUE THREAD

**Issue by shivprime94** [ControlCore-Project/concore-editor#150]
@pradeeban 

Road to generate: Make a graph edit an edge, and try to change the colour of the edge. I've attached an image of the issue.

![image](https://user-images.githubusercontent.com/73483959/227697934-53aa7742-a312-499b-836c-8a7a40d025d1.png)

Node version: v16.19.1
OS : Ubuntu 22.04.2 LTS
React ^17.0.2

**Comment by pradeeban** [comment]
Are you using http://controlcore-project.github.io/concore-editor or some other version? The above looks like DHGWorkflow. The color options for edges are removed in the concore editor.

The only option Edit Edge now has is "Label." Color and width cannot be changed.
