### ISSUE TITLE
Undo and Redo shortcuts on Ubuntu don't works as of now

### ISSUE THREAD

**Issue by shivprime94** [ControlCore-Project/concore-editor#151]
@pradeeban 
If you press ctrl+z ctrl+y it doesn't work
Node version: v16.19.1
OS : Ubuntu 22.04.2 LTS
React ^17.0.2

**Comment by pradeeban** [comment]
Ctrl+z and Ctrl+Shift+z in Mac work for me as undo and redo. I do not have access to Ubuntu at this point. I will keep this issue open.

**Comment by parteekcoder** [comment]
@pradeeban I tried this issue on Ubuntu , but not able to reproduce the issue

**Comment by pradeeban** [comment]
Yes, we couldn't reproduce either. It is likely @shivprime94's shortcuts are overridden by his custom settings.

Closing this. Please re-open if anyone can confirm the issue is present.
