### ISSUE TITLE
Zoom setter Slider not synched with the buttons

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#157]
When we click the buttons at the bottom right corner of the editor the slider next to it does not change its value

Which creates a confusion in the mind of user regarding the focus buttons

**Comment by parteekcoder** [comment]
Hi @pradeeban I think this issue can be closed , after testing at https://parteekcoder.github.io/concore-editor/

**Comment by pradeeban** [comment]
Thanks, closed.
