### ISSUE TITLE
Listing of program names can be confusing when there are too many files

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#168]
Edit node: The listing looks complex in naming nodes when there are too many files or folders.

The potential solution is to 
either,
just list the files in the first level (instead of recursively listing all the files in all the subdirectories.
or
filter the names based on the few characters the user inputs.

**Comment by Rahuljagwani** [comment]
@pradeeban 
 **"filter the names based on the few characters the user inputs."**
 This is still working you can check in https://rahuljagwani.github.io/concore-editor/

**Comment by pradeeban** [comment]
You are right. It works. It must be just a misunderstanding. Closing.
