### ISSUE TITLE
Run is disabled even after the build is complete

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#178]
The "Run" button must be enabled when the build is complete. Currently, the "Debug" is enabled. But "Run" is not. Both of them must be enabled at the same time.

@Rahuljagwani

**Comment by Rahuljagwani** [comment]
> The "Run" button must be enabled when the build is complete. Currently, the "Debug" is enabled. But "Run" is not. Both of them must be enabled at the same time.
> 
> @Rahuljagwani

Hi @pradeeban 

I remember me, Mark and you discussed it and the conclusion was that it does not make sense to "Run" immediately after building a study, "Debug" has to be executed in between. However, when output from "Debug" is cleared, then "Run" works.
I am not sure if I am completely correct, but I remember discussing it.

**Comment by Rahuljagwani** [comment]
made a PR: https://github.com/ControlCore-Project/concore-editor/pull/180

**Comment by pradeeban** [comment]
Merged. Thanks.
