### ISSUE TITLE
A placeholder localhost URL in place for the Server buttons

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#59]
concore editor is developed as a front-end for [concore](https://github.com/ControlCore-Project/concore/). However, currently, there is no seamless integration between the concore-editor and concore deployment. Currently, these server buttons (Build, Debug, Run, Clear, Stop, Destroy) do not do anything when clicked. Adding a sample URL from a localhost execution of concore FRI will provide a first step towards the integration with concore backend.

To identify and understand the concore APIs, please check the [test.py](https://github.com/ControlCore-Project/concore/blob/dev/fri/test.py) provided as part of concore FRI. Concore FRI (File Receiver Interface) functions as a python interface to expose concore methods as REST APIs.

To test this locally and implement it, one must perform the below steps:

* install [concore](https://github.com/ControlCore-Project/concore/) following the [installation guidelines](https://control-core.readthedocs.io/en/latest/installation.html).  
* install concore editor., following the [README](https://github.com/ControlCore-Project/concore-editor/blob/main/README.md).
* Run concore FRI as the backend following the [README](https://github.com/ControlCore-Project/concore/tree/dev/fri/README.md). 
* Test and confirm that FRI runs successfully through the [test.py](https://github.com/ControlCore-Project/concore/blob/dev/fri/test.py) method as indicated in the [README](https://github.com/ControlCore-Project/concore/tree/dev/fri).

Following the above steps, once the concore FRI runs, implement a similar strategy (similar to how [test.py](https://github.com/ControlCore-Project/concore/blob/dev/fri/test.py) functions as a client for [FRI](https://github.com/ControlCore-Project/concore/tree/dev/fri)) with concore editor in Javascript (React or a similar framework).

**Comment by parteekcoder** [comment]
hi @pradeeban  I would like to contribute in this project and be part of your GSOC projects this year can u please guide me

**Comment by pradeeban** [comment]
Hi and welcome, @parteekcoder. Please go through the README and previous discussions, also in https://github.com/NISYSLAB/Emory-BMI-GSoC/.

**Comment by parteekcoder** [comment]
Yeah can u please assign me some work so that I can understand better

**Comment by pradeeban** [comment]
Please feel free to attempt the open bugs.

**Comment by parteekcoder** [comment]
But there are not many issues ,may be u can suggest some improvements if want

**Comment by parteekcoder** [comment]
@pradeeban  is this issue still open to solve

**Comment by parteekcoder** [comment]
as there is already an PR for this issue

**Comment by pradeeban** [comment]
Yes, there is a PR on this that is currently open.

I recommend #58 or #45 instead.

**Comment by Rahuljagwani** [comment]
@pradeeban this issue can be closed after reviewing.

**Comment by pradeeban** [comment]
Thanks, @Rahuljagwani, for your contributions. Closing this issue now.
