### ISSUE TITLE
Enable empty node

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#62]
In [DHGWorkflow](https://pradeeban.github.io/DHGWorkflow/), we can have an empty node such as "OUT:" However, this cannot be created in concore-editor. It throws an error, "Node with incorrect label" when the second part of the label is left empty. This should be allowed, as an "Empty node."

See the ![Screenshot](https://github.com/ControlCore-Project/concore-editor/blob/main/figures/emptynode.png). This node naming should be allowed.

**Comment by Rahuljagwani** [comment]
I have solved this issue , just merging the previous issue #61 pull request will solve this issue also.
![image](https://user-images.githubusercontent.com/83580404/213251241-2b7c6a14-8307-4720-ab4b-e443c7949dfe.png)

**Comment by pradeeban** [comment]
Thanks a lot, @Rahuljagwani. This is fixed now in main with your contribution.
