### ISSUE TITLE
concore-editor does not run

### ISSUE THREAD

**Issue by pradeeban** [ControlCore-Project/concore-editor#7]
The below output was thrown in the browser for both http://localhost:3000/concore-editor and http://localhost:3000/DHGWorkflow, running from the dev branch as well as the main branch. Tested with both Firefox and Chrome.

Failed to compile

src/App.jsx
  Line 1:43:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 2:20:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 3:42:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 4:47:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 5:68:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 6:45:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 7:68:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 8:64:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 9:56:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 10:57:  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 11:55:  Expected linebreaks to be 'CRLF' 

........
.........
Search for the keywords to learn more about each error.

This error occurred during the build time and cannot be dismissed.

**Comment by pradeeban** [comment]
concore-Editor/DHGWorkflow is broken since pull request #4 is merged. The GitHub workflows fail with the same error, rendering https://controlcore-project.github.io/concore-editor/ unusable.


1m 58s
Run npm ci

added 1801 packages, and audited 1802 packages in 35s

2 packages are looking for funding
  run `npm fund` for details

45 vulnerabilities (1 low, 7 moderate, 26 high, 11 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> dhg-workflow@0.1.0 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

src/App.jsx
  Line 1:43:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 2:20:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 3:42:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 4:47:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 5:68:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  Line 6:45:   Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

**Comment by Aviral09** [comment]
Please do not run the --fix command as it may corrupt the git changes history and will show a lot of one endings changes. The simple fix for this issue is as follows -

In the .eslintrc.json change line 53 to "linebreak-style": ["error", "unix"]  if using a unix system. I have tried this fix on a new unix build.

**Comment by pradeeban** [comment]
Can you pls make a pull request with the changes?

**Comment by pradeeban** [comment]
The issue still persists, even after merging the changes to the main and dev branches.
