### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#70]
website is not responsive in small devices

**Comment by pradeeban** [comment]
Small devices, as in mobile devices? Which browser?
Can you please detail more?

**Comment by parteekcoder** [comment]
i am using chrome
@pradeeban 
to reproduce open in small devices like mobile or inspect the site and check responsiveness

**Comment by parteekcoder** [comment]
[Uploading screen-recorder-tue-feb-07-2023-23-22-57.webm…]()

**Comment by parteekcoder** [comment]
[screen-recorder-tue-feb-07-2023-23-22-57.webm](https://user-images.githubusercontent.com/100110395/217326854-0bbeff7f-affb-4e2f-812e-49ed347f3fcf.webm)

**Comment by pradeeban** [comment]
Please use a laptop or a computer for concore and concore-editor.

We use concore locally and therefore, concore-editor is not meant to be run from mobile devices. Because these devices anyway do not have the capability to run studies composed of Python and Matlab.

Therefore, closing this issue.
