### ISSUE TITLE
Ctrl+Shift+L Not working to close workspace (bug)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#79]
Recreate 

1. open app
2. create a workspace
3. press "Ctrl+Shift+L" 

Expected :- 
Should close the current workspace

Actual:- 

It is doing something else , In my window system it is starting some "Window Performance Log"

**Comment by pradeeban** [comment]
That is a very specific issue, unrelated to concore-editor. More likely related to the browser configurations or your system configuration.

**Comment by pradeeban** [comment]
Which operating system and browser are you using?

I tested on Mac OS on both Chrome and Firefox, and it works on both.

It prompts:
"Do you confirm to close the tab? This action is irreversable."

It is likely conflicting with something in your OS. I don't think our users are using any of these shortcuts. Especially they are not documented and so no one is aware. You can ignore the shortcuts if they are not working.

**Comment by parteekcoder** [comment]
> Which operating system and browser are you using?
> 
> I tested on Mac OS on both Chrome and Firefox, and it works on both.
> 
> It prompts: "Do you confirm to close the tab? This action is irreversable."
> 
> It is likely conflicting with something in your OS. I don't think our users are using any of these shortcuts. Especially they are not documented and so no one is aware. You can ignore the shortcuts if they are not working.


ok , I am using Window11  on chrome browser , on my system it starts "system performance logs"

**Comment by pradeeban** [comment]
Ok, please ignore the keyboard shortcuts.
