### ISSUE TITLE
Drag And Drop Not working (bug)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#81]
[screen-capture (3).webm](https://user-images.githubusercontent.com/100110395/218515483-08b4cd0b-a49e-4da2-85f4-625ef10d4f2b.webm)

When I tried to upload files(programs or graphml ) it it not working, I tested it on FireFox and Chrome Browser

**Comment by pradeeban** [comment]
Can you please elaborate on "Drag And Drop Not working?"

We did not expect concore editor to have drag-and-drop features. Please elaborate in screenshots or words. We cannot open webm files.

**Comment by parteekcoder** [comment]
As you have seen at many places to open a file instead of using "open dialog box" we simple drag our file there to open

concore-editor provide the feature of "drag and drop" files to open them, right??
As an window appeared to me when I tried to drop files there (you can see in the clip above )

**Comment by pradeeban** [comment]
Yes, "No video with supported format and MIME type found."

Also, as a best practice, avoid sharing videos on the bug reports. It limits accessibility. Screenshots work better.


"concore-editor provide the feature of "drag and drop" files to open them, right??"
No. 

1) Were you able to open any files by dragging and dropping? 

2) Are you referring to studies (graphml) or programs (basically, any text file, with or without any extension).

**Comment by pradeeban** [comment]
It is your browser showing the files to drop and open.

concore editor is not meant to open the files (graphml or program) through drag-and-drop.

The real issue here is the lack of document.

concore editor lacks any documentation and new users are left confused.

I am closing this as a "Won't Fix."
