### ISSUE TITLE
Drag And Drop Not so intutive (enhancement)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#82]
when I am exploring concore-editor and didn't know that I can even drap and Drop files

Suggestion :- UI of the left sidebar can be improved , so that users may know that they can also drag and drop

This we can also mention in our docs but I suggest it is more better that if we also we show this option on our UI as it increases User experience

**Comment by pradeeban** [comment]
": didn't know that I can even drap and Drop files"

What do you mean by "drag and drop files" from the left sidebar? Can you please elaborate?


I am not aware of that feature (unless one of the developers left an Easter Egg).

**Comment by parteekcoder** [comment]
I mean that on left sidebar , we should providec an option showing "drag and drop files" to open them

As it is no where seen on the concore-editor that It provide the option of opening the files by dragging and droping

**Comment by pradeeban** [comment]
"As it is no where seen on the concore-editor that It provide the option of opening the files by dragging and droping"

Yes, it is not an expected feature. (or am I misreading your report)?

How did you open a program by drag-and-dropping?

**Comment by parteekcoder** [comment]
![download](https://user-images.githubusercontent.com/100110395/218550322-5880139d-48a0-4c03-9840-d1f96663dd73.png)

Like this type of thing to upload program files

**Comment by pradeeban** [comment]
We do not support drag-and-drop in concore editor.

The options to open the files are:
1. Open the individual studies (graphml).
2. Open the whole folder with programs (anything textual actually. but mostly .py, .cpp, .m, .v, ...) via "Upload Directory."

**Comment by pradeeban** [comment]
Closing for the same reason as #81.

We lack documentation.

Hopefully, as part of the GSoC project idea, the contributor will pay more attention to make a documentation that supports new users to get started.

**Comment by parteekcoder** [comment]
hey @pradeeban , are you not keeping it as an enhancement feature

**Comment by pradeeban** [comment]
No, @parteekcoder.

At this point, I recommend you look at the open bugs and understand concore through the paper. While I appreciate your Q&A effort, we should use the time (both yours as a contributor and ours as a mentor) more effectively.

**Comment by pradeeban** [comment]
The concore repository is at https://github.com/ControlCore-Project/concore (which is to be integrated with concore editor).

**Comment by parteekcoder** [comment]
> I understand the pain of using new software without proper user documentation. Being a research organization, we should pay more attention to documentation. We will make that a top priority for the GSoC 2023 projects.
> 
> Thanks for your contributions and efforts.

yeah , Along with the interation I can also help in building documentation

Is there any documentation existing now for concore editor?
If not we can create a "docs" project for concore editor along with integration

**Comment by pradeeban** [comment]
The only documentation we have for concore editor is the README file. We need documentation with screenshots.

We cannot have "Docs" only projects as part of GSoC (that is against the rules of GSoC. GSoC projects must be primarily development tasks).

The project idea [1] An Integrated CONTROL-CORE experience. should incorporate the documentation. It is not a difficult undertaking. Just documentation was left as a second-throught in some of the past GSoC projects as we paid more attention to developing.
