### ISSUE TITLE
Not An option to upload files (Question)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#86]
As we are building files at server but there is not any option to upload files to server
![image](https://user-images.githubusercontent.com/100110395/219944794-6ebd1cc5-90b5-4bcf-90a2-139fad32aef2.png)

Also we are writing uploading and writing files at server , then it will be difficult to request at which last server we stored the files and ran

Do I understood it right? @pradeeban

**Comment by Rahuljagwani** [comment]
Hello @parteekcoder. Actually the whole project is about integrating files from frontend and send them to backend server. For now all URLs are hardcoded so at GSOC coding period time we have to implement it.

**Comment by parteekcoder** [comment]
> Hello @parteekcoder. Actually the whole project is about integrating files from frontend and send them to backend server. For now all URLs are hardcoded so at GSOC coding period time we have to implement it.

yeah, but I just want to mention here that there should be a button (in the server buttons) to upload files

**Comment by Rahuljagwani** [comment]
> > Hello @parteekcoder. Actually the whole project is about integrating files from frontend and send them to backend server. For now all URLs are hardcoded so at GSOC coding period time we have to implement it.
> 
> yeah, but I just want to mention here that there should be a button (in the server buttons) to upload files

If you mean python and graphml files such as (controller.py, pm.py, sample.graphml etc), then "Upload directory" will do the same and integration should be done in such a way (Whole GSOC project is about this) that using uploaded files user should be able to perform build, debug, clear etc. and output must be shown.
I think confusion is there as there is "upload files" function in main.py in concore-server. It is there because for now the real users who are using it for researching are invoking functions from CLI so there must be a way to upload files from CLI. But after the Integration will be done, the users just have to upload files in concore-editor and just click on the functions to run them.
Whole purpose of concore-editor is this.
A clarification by @pradeeban on what I just wrote will be great.
@parteekcoder If you have any other doubts regarding this or any other discussion please fell free to open it up in https://github.com/ControlCore-Project/concore-editor/discussions as it will also help other users.

**Comment by Rahuljagwani** [comment]
@parteekcoder  Let this issue be opened until @pradeeban clarifies.
Thank You

**Comment by pradeeban** [comment]
@Rahuljagwani's interpretation is right.

There are currently two options to "upload" files, which basically load the files from local into browser's memory:
"Open" uploads the GraphML files, which represent the *studies*.
"Upload Directory" uploads the whole folder structure, which usually consists of the *studies* (as graphml files) and *programs* that are part of the studies (the python, matlab, c++, .... files) and any other files that must be part of the execution.

This GSoC project will integrate the concore (backend) and concore editor (frontend), which now mostly function independently. At the time, we should discuss how this is done and if we can "upload" files to a "server." Mostly, we are still seeing concore as a local version. That is, concore running on your laptop with concore editor either running in your laptop also (or on the github.io, which is the approach we usually take). So we don't really see a "server" to upload, although that is a totally valid and potential use case. The catch with the server use case is it will need more developments on security and privacy front.

This is more of a design discussion. In your GSoC proposals, please include your design choices and approaches. Then we will individually comment on your approaches (if any clarification is necessary).

Closing this issue. But please feel free to open a discussion at https://github.com/ControlCore-Project/concore-editor/discussions if you like to discuss your design choices in detail before the proposal.

**Comment by Rahuljagwani** [comment]
> @Rahuljagwani's interpretation is right.
> 
> There are currently two options to "upload" files, which basically load the files from local into browser's memory: "Open" uploads the GraphML files, which represent the _studies_. "Upload Directory" uploads the whole folder structure, which usually consists of the _studies_ (as graphml files) and _programs_ that are part of the studies (the python, matlab, c++, .... files) and any other files that must be part of the execution.
> 
> This GSoC project will integrate the concore (backend) and concore editor (frontend), which now mostly function independently. At the time, we should discuss how this is done and if we can "upload" files to a "server." Mostly, we are still seeing concore as a local version. That is, concore running on your laptop with concore editor either running in your laptop also (or on the github.io, which is the approach we usually take). So we don't really see a "server" to upload, although that is a totally valid and potential use case. The catch with the server use case is it will need more developments on security and privacy front.
> 
> This is more of a design discussion. In your GSoC proposals, please include your design choices and approaches. Then we will individually comment on your approaches (if any clarification is necessary).
> 
> Closing this issue. But please feel free to open a discussion at https://github.com/ControlCore-Project/concore-editor/discussions if you like to discuss your design choices in detail before the proposal.

Thank You for clarification.
Definitely going to discuss the design choices.
