### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#88]
It should ask the user which directory and graphml file to build , debug, run etc

https://github.com/ControlCore-Project/concore-editor/blob/main/src/graph-builder/graph-core/6-server.js#L70

Here before making request it should prompt user for these informations

**Comment by Rahuljagwani** [comment]
Hello @parteekcoder, paths are hardcoded for now only as told by @pradeeban. You can refer to https://github.com/ControlCore-Project/concore-editor/pull/65 and issue#58 to understand this.

**Comment by parteekcoder** [comment]
thanks @Rahuljagwani ,
@pradeeban I am closing this issue

**Comment by pradeeban** [comment]
Yes. Before the hard-coded path, there was not even an integration. This is our baby step. :) The actual implementation is part of the GSoC.
