### ISSUE TITLE
App crashes in development and production (critical bug)

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#92]
Reproduce

1. Open app
2. Create some nodes and edges
3. click on any node or edge and delete it using delete option in navbar
4. You will see edit is still enabled
5. Click `edit`
6. it creashes

**Comment by parteekcoder** [comment]
@pradeeban you can check here 

If there is anything , please tell me so that I will update that

**Comment by pradeeban** [comment]
This is a great catch. Good QA job, @parteekcoder!

It is a bug that has existed since the DHGWorkflow days (2021). We just never noticed it. https://nisyslab.github.io/DHGWorkflow/

**Comment by parteekcoder** [comment]
> This is a great catch. Good QA job, @parteekcoder!
> 
> It is a bug that has existed since the DHGWorkflow days (2021). We just never noticed it. https://nisyslab.github.io/DHGWorkflow/

thanks @pradeeban for the comment

I think I have proved my Skills like:

- Analysis
- Coding
- Problem Solving
- Discussion
- Open to new challenges
- debugging
and many more

I will look for more improvements to be done or bug if any

**Comment by pradeeban** [comment]
Yes, of course. I hope you enjoy the time. Sorry for the slow merge at times. I am just careful not to introduce new bugs with quick merging.

Aviral's suggestion of merging to dev could work. But then again, it just postpones the testing from my end to a future day when I have to merge back to the main.

I will test your PR shortly.

**Comment by pradeeban** [comment]
Merged #93. Thanks @parteekcoder.
