### ISSUE TITLE
Title bar does not changes to 'untitled' when all graphs are closed

### ISSUE THREAD

**Issue by Rahuljagwani** [ControlCore-Project/concore-editor#94]
To Reproduce the issue:
1. Click on https://controlcore-project.github.io/concore-editor/
2. Upload any directory with graphml files.
3. After closing all graphml files, the title bar will still show the name of last graphml file instead it must show 'untitled' .

![imgissue1](https://user-images.githubusercontent.com/83580404/220696181-d854d308-06fd-4d71-bd95-b7109c0d2e66.png)

**Comment by pradeeban** [comment]
Thanks @Rahuljagwani

**Comment by Rahuljagwani** [comment]
@pradeeban 
I don't know why but this issue is appearing again. It can be fixed with a minor change, but removing that particular graph from the present graph array is a problem. I mean the closed graph is not getting removed from the graph array when that particular graph is closed from the tab bar.
So should I fix this by keeping the above behavior?

**Comment by pradeeban** [comment]
@Rahuljagwani, It is a trivial bug either way. If you think the fix does not break anything, you can give it a try. Just remembered I haven't triggered a deployment to control-core repository's concore-editor for a long time.

Will trigger the page deploy action shortly.
