### ISSUE TITLE
History still visible when all graphs are closed.

### ISSUE THREAD

**Issue by Rahuljagwani** [ControlCore-Project/concore-editor#97]
To Reproduce:
1. Open any number of graphs.
2. Upon closing all of them history is still visible.

The issue doesn't seem big but upon clicking restore, nothing is happening.

![issue history](https://user-images.githubusercontent.com/83580404/221173456-5604f0b8-69d1-45e9-9c36-0d44161ee3cb.png)

**Comment by parteekcoder** [comment]
@pradeeban I think that is not an issue, As in chrome bowser history also persists even when we close the tabs

**Comment by parteekcoder** [comment]
As history accounts for what work we have done in past not the work we are doing now , is @pradeeban this is correct

**Comment by parteekcoder** [comment]
Oh ! I think name of the issue should be `not able to restore history`

**Comment by pradeeban** [comment]
The issue @Rahuljagwani reported is once you close the study, its (the last-closed graphml) history is still visible. It is a valid issue (although it does not bother us much).

I will test and merge shortly.

There is also a bigger issue with how history is handled for studies. But that is for a separate discussion.

**Comment by Rahuljagwani** [comment]
> As history accounts for what work we have done in past not the work we are doing now , is @pradeeban this is correct

Hi @parteekcoder , you are absolutely correct about the browser history thing.
But case here is little different as when we close last graph history remains visible in history modal and it is not possible to restore any state of it as variables curGraphIndex and curGraphInstance will become 0 and null respectively. So no point in showing last graphs history.

One point you mentioned about browser tab history can be good extension in concore-editor i.e. it will contain history of all graphs or studies loaded and removed.

**Comment by Rahuljagwani** [comment]
> The issue @Rahuljagwani reported is once you close the study, its (the last-closed graphml) history is still visible. It is a valid issue (although it does not bother us much).
> 
> I will test and merge shortly.
> 
> There is also a bigger issue with how history is handled for studies. But that is for a separate discussion.

Sure we will discuss on it.

**Comment by pradeeban** [comment]
When Shubham implemented DHGWorkflow during his GSoC 2021, he had visions for sharing the graphs across multiple users through a server version, and thus a stronger reason for maintaining history. When Aviral adopted DHGWorkflow for concore as the concore editor during his GSoC 2022, we had already moved away from the ideas of such a collaborative server environment. So, while it is still a neat feature, the history feature is rarely used anymore. That explains the untested issues and bugs you have found (and will find) in the history feature. @parteekcoder @Rahuljagwani

**Comment by Rahuljagwani** [comment]
> When Shubham implemented DHGWorkflow during his GSoC 2021, he had visions for sharing the graphs across multiple users through a server version, and thus a stronger reason for maintaining history. When Aviral adopted DHGWorkflow for concore as the concore editor during his GSoC 2022, we had already moved away from the ideas of such a collaborative server environment. So, while it is still a neat feature, the history feature is rarely used anymore. That explains the untested issues and bugs you have found (and will find) in the history feature. @parteekcoder @Rahuljagwani 

Understood, I will keep this in mind while testing.
